# Generated by Django 5.2.4 on 2025-07-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('images', models.ImageField(upload_to='images/')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
